DMDcoin/diamond-node

- Cargo.lock
- Cargo.toml
- bin/oe/lib.rs
- bin/oe/reserved_peer_management.rs
- bin/oe/run.rs
- crates/ethcore/src/client/client.rs
- crates/ethcore/src/client/test_client.rs
- crates/ethcore/src/client/traits.rs
- crates/ethcore/src/engines/hbbft/contracts/staking.rs
- crates/ethcore/src/engines/hbbft/contracts/validator_set.rs
- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
- crates/ethcore/src/engines/hbbft/hbbft_message_memorium.rs
- crates/ethcore/src/engines/hbbft/hbbft_peers_management.rs
- crates/ethcore/src/engines/hbbft/hbbft_state.rs
- crates/ethcore/src/ethereum/public_key_to_address.rs
- crates/net/fetch/src/client.rs
- crates/rpc/src/v1/tests/eth.rs
- crates/transaction-pool/src/tests/tx_builder.rs
- crates/util/cli-signer/rpc-client/Cargo.toml
- crates/util/panic-hook/Cargo.toml
- crates/vm/evm/benches/basic.rs
Pull Request for integrating the reserved peers management (https://github.com/DMDcoin/diamond-node/issues/5)
(caution: contract support required for this feature)
Also contains large parts of the hbbft message memorium: https://github.com/DMDcoin/openethereum-3.x/issues/17
> I5 reserved peers management

- Cargo.lock
- Cargo.toml
- crates/ethcore/src/client/client.rs
- crates/ethcore/src/engines/hbbft/hbbft_config_generator/src/main.rs
- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
- crates/ethcore/src/engines/hbbft/hbbft_message_memorium.rs
- crates/ethcore/src/engines/mod.rs
- crates/util/stats/Cargo.toml
- crates/util/stats/src/lib.rs
- solved deadlock caused by prometheus interface: https://github.com/DMDcoin/diamond-node/issues/13
-  https://github.com/DMDcoin/diamond-node/issues/14
> Prometheus provides now hbbft data.

- Cargo.lock
- crates/ethcore/src/engines/hbbft/hbbft_message_memorium.rs
- crates/util/stats/src/lib.rs
using labels now for https://github.com/DMDcoin/diamond-node/issues/14
> using prometheus labels now for hbbft specific gauges

- crates/ethcore/src/engines/hbbft/hbbft_message_memorium.rs
- crates/util/stats/src/lib.rs
merged fix for hbbft consensus values (not using labels anymore)
> I14 fix hbbft consensus values

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/ethcore/src/engines/hbbft/hbbft_message_memorium.rs
- crates/util/version/Cargo.toml
Hotfix release 0.8.7 
- removed deadlock detection from default config
- added missing categorisation from hbbft_message_memorium
- increased sleeping timer for hbbft_message_memoriumto increase performance, since we often have messages that can't be processed.
> Hotfix release 0.8.7

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/ethcore/src/engines/hbbft/contracts/keygen_history.rs
- crates/util/version/Cargo.toml
see: https://github.com/DMDcoin/openethereum-3.x/issues/72
> reimplmeneted trigger timestamp for legacy protocol v1 support.

- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
- crates/ethcore/src/engines/hbbft/hbbft_message_memorium.rs
solving https://github.com/DMDcoin/diamond-node/issues/29
> I29 log spam from syncing nodes

- crates/ethcore/src/client/client.rs
adding is_major_syncing gauge
https://github.com/DMDcoin/diamond-node/issues/32
> added gauge

- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
https://github.com/DMDcoin/diamond-node/issues/40
> Integrating feature into dev: I40 transaction fee distribution

- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
Merge error by me: Reverts DMDcoin/diamond-node#should be integrated into dev branch.
> Revert "Integrating feature into dev: I40 transaction fee distribution"

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bin/oe/blockchain.rs
- bin/oe/cli/mod.rs
- bin/oe/configuration.rs
- bin/oe/helpers.rs
- bin/oe/run.rs
- bin/oe/snapshot.rs
- crates/ethcore/src/client/client.rs
- crates/ethcore/src/client/config.rs
- crates/ethcore/src/client/traits.rs
- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
- crates/util/version/Cargo.toml
- crates/util/version/src/lib.rs
[Autoshutdown after a period of 30 minutes without block import](https://github.com/DMDcoin/diamond-node/issues/78)
> Release 0.9.3

- crates/concensus/ethash/src/shared.rs
- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
- crates/ethcore/src/engines/hbbft/hbbft_message_memorium.rs
- crates/ethcore/src/miner/pool_client.rs
- crates/ethcore/sync/src/chain/mod.rs
Except for in hbbft_peers_management.rs.
> Fixed warnings

- Cargo.lock
- crates/ethcore/src/engines/hbbft/contracts/keygen_history.rs
- crates/ethcore/src/engines/hbbft/hbbft_config_generator/Cargo.toml
- crates/ethcore/src/engines/hbbft/hbbft_config_generator/src/keygen_history_helpers.rs
- crates/ethcore/src/engines/hbbft/hbbft_config_generator/src/main.rs
- crates/ethcore/src/engines/hbbft/hbbft_state.rs
https://github.com/DMDcoin/diamond-node/issues/112
> i112 key gen as hex

- crates/ethcore/src/engines/hbbft/contracts/keygen_history.rs
- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
- crates/ethcore/src/engines/hbbft/hbbft_state.rs
This solves the problem that the Node Software crashes instantly after booting up, if there is a problem with the sync key gen.
https://github.com/DMDcoin/diamond-node/issues/123
> I123 sync keygen error

- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
https://github.com/DMDcoin/diamond-node/issues/130
> logging transactions for block that gets created.

- .github/workflows/build-test.yml
- Cargo.lock
- crates/concensus/miner/Cargo.toml
- crates/concensus/miner/src/service_transaction_checker.rs
- crates/ethcore/Cargo.toml
- crates/ethcore/src/engines/hbbft/hbbft_network_fork_manager.rs
- crates/net/node-filter/Cargo.toml
merging: https://github.com/DMDcoin/diamond-node/issues/120
this closes also the PR that fails because of CI mess ups: https://github.com/DMDcoin/diamond-node/pull/139
> I120 merge remove registry

- CHANGELOG.md
- crates/ethcore/src/client/client.rs
- crates/ethcore/src/engines/hbbft/hbbft_early_epoch_end_manager.rs
- crates/ethcore/src/engines/hbbft/hbbft_message_memorium.rs
Early Epoch End trigger condition is now time Based (15 minutes) instead of block based (10 Blocks) https://github.com/DMDcoin/diamond-node/issues/87
Stage 5 Verification Logging Imrpovements: https://github.com/DMDcoin/diamond-node/issues/147
> Early Epoch End: Time based trigger condition & improved logging for Stage 5 Errors.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
- crates/ethcore/src/engines/hbbft/hbbft_state.rs
- crates/util/version/Cargo.toml
- [Nodes that are not a active validator seem to try to send connectivity reports] (https://github.com/DMDcoin/diamond-node/issues/153)
>  inconnectivity reports for non validators

- .github/workflows/build-test.yml
- .github/workflows/check.yml
- .github/workflows/fmt.yml
- Cargo.lock
- bin/oe/db/rocksdb/mod.rs
- crates/ethcore/src/client/client.rs
- crates/ethcore/src/engines/hbbft/block_reward_hbbft.rs
- crates/ethcore/src/engines/hbbft/hbbft_early_epoch_end_manager.rs
- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
- crates/ethcore/src/engines/hbbft/hbbft_engine_cache.rs
- crates/ethcore/src/engines/hbbft/hbbft_message_memorium.rs
- crates/ethcore/src/engines/hbbft/hbbft_state.rs
- crates/ethcore/src/engines/hbbft/keygen_transactions.rs
- crates/ethcore/src/engines/hbbft/mod.rs
- crates/ethcore/sync/src/api.rs
- crates/ethcore/sync/src/chain/handler.rs
- crates/net/network-devp2p/Cargo.toml
- crates/net/network-devp2p/src/host.rs
- crates/net/network-devp2p/src/lib.rs
- crates/net/network-devp2p/src/node_table.rs
- crates/net/network-devp2p/src/service.rs
- "No Session Exists": https://github.com/DMDcoin/diamond-node/issues/150
- Lock overhead reduction for validator actions
- Connect & Disconnect Report management: fixed double sending of reports: https://github.com/DMDcoin/diamond-node/issues/157
- Stage 3 Verification: Fixed State Pruning related error. https://github.com/DMDcoin/diamond-node/issues/161
- Added Network and DevP2P related Informations to the Prometheus Metrics: https://github.com/DMDcoin/diamond-node/issues/163
- Early Epoch End: Treat any HBBFT Message as being a responsive partner node: https://github.com/DMDcoin/diamond-node/issues/87
> Release 0.9.8

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/accounts/ethkey/Cargo.toml
- crates/util/version/Cargo.toml
release 0.10
reverted secp256k1 reference to parity
> Release prep 0.10.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/ethcore/sync/src/chain/handler.rs
- crates/util/version/Cargo.toml
> Release 0.10.0 - final 

- .github/workflows/compile-targets.yml
- crates/ethcore/src/engines/hbbft/hbbft_peers_management.rs
- crates/ethcore/sync/src/api.rs
- crates/ethcore/sync/src/chain/handler.rs
- crates/ethcore/sync/src/chain/mod.rs
- crates/ethcore/sync/src/chain/propagator.rs
- crates/ethcore/sync/src/chain/propagator_statistics.rs
- crates/ethcore/sync/src/tests/helpers.rs
prometheus monitoring implementation for https://github.com/DMDcoin/diamond-node/issues/163
> I163 network usage monitoring sync

- crates/ethcore/src/lib.rs
- crates/ethcore/sync/src/chain/handler.rs
- crates/ethcore/sync/src/chain/requester.rs
- crates/ethcore/sync/src/chain/supplier.rs
- default.nix
This pull request includes several changes aimed at improving logging granularity, removing unused dependencies, and adding a development environment configuration. Below is a summary of the most important changes grouped by theme:
* Changed logging level from `info!` to `debug!` in multiple locations within the `SyncHandler`, `SyncRequester`, and `SyncSupplier` implementations to reduce verbosity in logs for pooled transactions. (`crates/ethcore/sync/src/chain/handler.rs` [[1]](diffhunk://#diff-ebdcd3037adb3e2b02fd2937121cad46e02dabdd8d95f3dfa67df2e7f53aafc2L899-R899) `crates/ethcore/sync/src/chain/requester.rs` [[2]](diffhunk://#diff-587f3320ce84a569f7a30ac3afee85351635867e0b737c00207d23975288372bL116-R116) `crates/ethcore/sync/src/chain/supplier.rs` …
> Prep release 0.11.0 rc2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/ethcore/sync/src/block_sync.rs
- crates/ethcore/sync/src/chain/supplier.rs
- crates/ethcore/sync/src/tests/chain.rs
- crates/net/network-devp2p/src/connection.rs
- crates/net/network-devp2p/src/host.rs
- crates/net/network-devp2p/src/session.rs
- crates/net/network/src/client_version.rs
- crates/util/version/Cargo.toml
- Emergency fix to improve blockimports: only one block at a time is now requested throught the devp2p block sync protocol. https://github.com/DMDcoin/diamond-node/issues/209
> Release 0.10.1 : Hotfix i209 unsyncable blocks

- crates/ethcore/sync/src/chain/mod.rs
implementation for https://github.com/DMDcoin/diamond-node/issues/223
> SyncStatus caching implementation

- crates/ethcore/src/engines/hbbft/hbbft_engine.rs
- crates/ethcore/src/engines/hbbft/utils/mod.rs
- crates/ethcore/src/engines/hbbft/utils/transactions_shuffling.rs
https://github.com/DMDcoin/diamond-node/issues/89
> diamond front running resistance: applying the transaction shuffeling

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/ethcore/sync/src/chain/propagator.rs
- crates/net/network-devp2p/src/session_container.rs
- crates/util/version/Cargo.toml
> Version update v 0.11.6

- crates/net/network-devp2p/src/host.rs
- crates/net/network-devp2p/src/session_container.rs
fixes: https://github.com/DMDcoin/diamond-node/issues/267
> deregister_session_stream can cause deadlocks

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/net/network-devp2p/src/host.rs
- crates/net/network-devp2p/src/session_container.rs
- crates/util/version/Cargo.toml
-  [deregister_session_stream can cause deadlocks](https://github.com/DMDcoin/diamond-node/issues/267)
> release 0.11.8
